// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Hpc.Rest.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Defines headers for getJobs operation.
    /// </summary>
    public partial class GetJobsHeaders
    {
        /// <summary>
        /// Initializes a new instance of the GetJobsHeaders class.
        /// </summary>
        public GetJobsHeaders()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GetJobsHeaders class.
        /// </summary>
        /// <param name="xMsContinuationQueryId">Enables large sets of data to
        /// be returned in smaller responses across a continuation sequence of
        /// several requests. The value of this header is to be assigned to the
        /// _queryId_ query parameter in the next call of the sequence of calls
        /// to this API. The response contains this header as long as
        /// additional data remains to be processed.
        ///
        /// The format of the data in this header is not guaranteed to remain
        /// unchanged. You should only copy the data in this header from one
        /// operation in a set of multiple operations to the _queryId_ URI
        /// parameter for the next operation. You should not use the data in
        /// this header or depend on the format of the data in this header in
        /// any other way.
        /// </param>
        public GetJobsHeaders(string xMsContinuationQueryId = default(string))
        {
            XMsContinuationQueryId = xMsContinuationQueryId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets enables large sets of data to be returned in smaller
        /// responses across a continuation sequence of several requests. The
        /// value of this header is to be assigned to the _queryId_ query
        /// parameter in the next call of the sequence of calls to this API.
        /// The response contains this header as long as additional data
        /// remains to be processed.
        ///
        /// The format of the data in this header is not guaranteed to remain
        /// unchanged. You should only copy the data in this header from one
        /// operation in a set of multiple operations to the _queryId_ URI
        /// parameter for the next operation. You should not use the data in
        /// this header or depend on the format of the data in this header in
        /// any other way.
        ///
        /// </summary>
        [JsonProperty(PropertyName = "x-ms-continuation-queryId")]
        public string XMsContinuationQueryId { get; set; }

    }
}
