// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Hpc.Rest.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class MetricInstanceData
    {
        /// <summary>
        /// Initializes a new instance of the MetricInstanceData class.
        /// </summary>
        public MetricInstanceData()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MetricInstanceData class.
        /// </summary>
        public MetricInstanceData(string instanceName = default(string), IList<MetricInstanceDataValuesItem> values = default(IList<MetricInstanceDataValuesItem>))
        {
            InstanceName = instanceName;
            Values = values;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "InstanceName")]
        public string InstanceName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Values")]
        public IList<MetricInstanceDataValuesItem> Values { get; set; }

    }
}
