// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Hpc.Rest.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class MetricInstanceDataValuesItem
    {
        /// <summary>
        /// Initializes a new instance of the MetricInstanceDataValuesItem
        /// class.
        /// </summary>
        public MetricInstanceDataValuesItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MetricInstanceDataValuesItem
        /// class.
        /// </summary>
        public MetricInstanceDataValuesItem(string key = default(string), double? value = default(double?))
        {
            Key = key;
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Key")]
        public string Key { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Value")]
        public double? Value { get; set; }

    }
}
