// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Hpc.Rest.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class NodeGroupOperation
    {
        /// <summary>
        /// Initializes a new instance of the NodeGroupOperation class.
        /// </summary>
        public NodeGroupOperation()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NodeGroupOperation class.
        /// </summary>
        /// <param name="operation">Possible values include: 'add',
        /// 'remove'</param>
        public NodeGroupOperation(string groupName = default(string), string operation = default(string), IList<string> nodeNames = default(IList<string>))
        {
            GroupName = groupName;
            Operation = operation;
            NodeNames = nodeNames;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "GroupName")]
        public string GroupName { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'add', 'remove'
        /// </summary>
        [JsonProperty(PropertyName = "Operation")]
        public string Operation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NodeNames")]
        public IList<string> NodeNames { get; set; }

    }
}
