// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Hpc.Rest.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class NodeGroup
    {
        /// <summary>
        /// Initializes a new instance of the NodeGroup class.
        /// </summary>
        public NodeGroup()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NodeGroup class.
        /// </summary>
        public NodeGroup(string name = default(string), string description = default(string), bool? managed = default(bool?))
        {
            Name = name;
            Description = description;
            Managed = managed;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Managed")]
        public bool? Managed { get; set; }

    }
}
