// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Hpc.Rest.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class NodeMetric
    {
        /// <summary>
        /// Initializes a new instance of the NodeMetric class.
        /// </summary>
        public NodeMetric()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NodeMetric class.
        /// </summary>
        public NodeMetric(string nodeName = default(string), IDictionary<string, double?> metrics = default(IDictionary<string, double?>))
        {
            NodeName = nodeName;
            Metrics = metrics;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NodeName")]
        public string NodeName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Metrics")]
        public IDictionary<string, double?> Metrics { get; set; }

    }
}
