// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Hpc.Rest.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class RestObject
    {
        /// <summary>
        /// Initializes a new instance of the RestObject class.
        /// </summary>
        public RestObject()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RestObject class.
        /// </summary>
        public RestObject(IList<RestProperty> properties = default(IList<RestProperty>))
        {
            Properties = properties;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Properties")]
        public IList<RestProperty> Properties { get; set; }

    }
}
